In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
titanic=sns.load_dataset('titanic')
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [47]:
a=np.arange (0,10,1)
a
## To check the dimension of the array you use 
a.ndim
## To ge the shape of the array
a.shape
##Get the type and size
a.dtype
a.size ## total no of elements
a.nbytes
a.itemsize
a.nbytes


40

In [49]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])## This is a two by seven matrix
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [50]:
a.shape

(2, 7)

In [54]:
##To get a specific elementm[r,c]
a[1, 5]

13

In [55]:
a[1,-2]

13

In [56]:
## To get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
## Get a specific column
a[:,0]

array([1, 8])

In [ ]:
## GEtting more fancyn[startindex:endindex:stepsize]
a[n]

In [19]:
## 2Dimensional allay
import numpy as np
a=np.array([7.0,6.0,5.0],[3.0,2.0,1.0])
a

TypeError: Field elements must be 2- or 3-tuples, got '3.0'

In [2]:
print(2+2)

4


In [6]:
1+1

2

In [11]:
## Array creation
hum=np.arange(1,10,1)
hum
## The above lists the numbers from one to 9 in an interval of one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
njeri=np.arange(1,20,5)## 5 is called a step value or the range at which the numbers zitaachana
njeri

array([ 1,  6, 11, 16])

In [16]:
## Linspace() funcrion 
humk=np.linspace(0,10,10)
humk

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [19]:
## np.ones()generates an array made of ones only
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
##np.eye()used to create an identity matrix
np.eye(4)
np.eye(4,3) ## 4 rows and 3 columns
np.eye(4,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]])

In [18]:
## np.zeros() It generates an array set of zeros
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [28]:
## Random functions
## It is used to generate a  random list of numbers
np.random.rand(4,5) # 4*5 Dimensional matrix
np.random.rand(5 )# a one dimensional array
np.random.randn(4) ## used for generating a one d array with a normal dist

array([-0.54596784,  0.17728157,  1.33872653, -2.25715444])

In [4]:
print ("I Love Hum")

I Love Hum


In [5]:
import random
def gameWin(comp,you):
    if comp==you:
        return None
    elif comp=='r':
        if you=='p':
            return True
        elif you=='s':
            return False
    elif comp=='p':
            if you=='r':
                return False
            elif you =='s':
                return True
    elif comp=='s':
        if you=='r':
            return True
        elif you=='p':
            return False

print("comp turn: Rock(r), paper(p),scissor(s)")
randN = random.randint(1,3)
print(randN)
if randN==1:
    comp='r'
elif randN==2:
    comp='p'
elif randN==3:
    comp='s'
you=input('your turn: Rock(r),paper(p),scissors(s)')
a= gameWin(comp,you)
print(f"comp choose",comp)
print(f"you choose",you)
if a==None:
    print('this game is tie!')
elif a:
    print('Congraturations you won!')
else:
    print('you lose!')

comp turn: Rock(r), paper(p),scissor(s)
3
your turn: Rock(r),paper(p),scissors(s)r
comp choose s
you choose r
Congraturations you won!


hum
